### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by yokimohan123** [payfort/start-php#8]
Hello team Payfort, i have integrated the payfort plugin in my shop, and i want to do the validation for while payment for invalid card details, how is this possible i have using simple try and catch block, but it's no use, and it's not working anymore, so please help me to do the validation part especially on card details, Thanks in advance.

**Comment by alovak** [comment]
Hi!

In rare cases you will provide/use card details with start-php (because of security reasons and need to be PCI DSS Compliant). You have to use tokenization. For web applications we provide JS library https://docs.start.payfort.com/guides/beautiful.js/. You can find how to use it with start-php following the link.
